"use server";

import { db } from "@/db/index";
import { users } from "@/db/auth-schema";
import { usersProfiles } from "@/db/user-schema";
import { results } from "@/db/learning-schema";
import { auth } from "@/lib/auth";
import { randomUUID } from "crypto";
import { z } from "zod";
import type { Persona } from "@/db/types";

// Realistic name pools for demo data
const FIRST_NAMES = [
  "Alex",
  "Jordan",
  "Taylor",
  "Morgan",
  "Casey",
  "Riley",
  "Avery",
  "Quinn",
  "Sage",
  "River",
  "Skyler",
  "Phoenix",
  "Rowan",
  "Blake",
  "Cameron",
  "Dakota",
  "Jamie",
  "Kai",
  "Logan",
  "Noah",
  "Emma",
  "Olivia",
  "Sophia",
  "Isabella",
  "Mia",
  "Charlotte",
  "Amelia",
  "Harper",
  "Evelyn",
  "Abigail",
  "Emily",
  "Elizabeth",
  "Sofia",
  "Avery",
  "Ella",
  "Madison",
  "Scarlett",
  "Victoria",
  "Aria",
  "Grace",
  "Chloe",
  "Lily",
  "Natalie",
  "Zoe",
  "Hannah",
  "Lillian",
  "Addison",
  "Eleanor",
  "Aubrey",
  "Layla",
  "Zoey",
  "Penelope",
  "Riley",
  "Leah",
  "Audrey",
  "Savannah",
  "Allison",
  "Samantha",
  "Nora",
  "Skylar",
  "Camila",
  "Anna",
  "Paisley",
  "Ariana",
  "Ellie",
  "Aaliyah",
  "Claire",
  "Violet",
  "Stella",
  "Lucy",
  "Paisley",
  "Bella",
  "Caroline",
  "Genesis",
  "Alyssa",
  "Kennedy",
  "Kinsley",
  "Allison",
  "Maya",
  "Willow",
  "Naomi",
  "Elena",
  "Sarah",
  "Arianna",
  "Alice",
  "Madelyn",
  "Cora",
  "Ruby",
  "Eva",
  "Serenity",
  "Autumn",
  "Adeline",
  "Hailey",
  "Gianna",
  "Valentina",
  "Isla",
  "Eliana",
  "Quinn",
  "Nevaeh",
  "Ivy",
  "Sadie",
  "Piper",
  "Lydia",
  "Alexa",
  "Joseph",
  "Michael",
  "William",
  "James",
  "Benjamin",
  "Lucas",
  "Henry",
  "Alexander",
  "Mason",
  "Ethan",
  "Daniel",
  "Matthew",
  "Aiden",
  "Jackson",
  "Sebastian",
  "David",
  "Carter",
  "Wyatt",
  "Jayden",
  "John",
  "Owen",
  "Dylan",
  "Luke",
  "Gabriel",
  "Anthony",
  "Isaac",
  "Grayson",
  "Jack",
  "Julian",
  "Levi",
  "Christopher",
  "Joshua",
  "Andrew",
  "Lincoln",
  "Mateo",
  "Ryan",
  "Jaxon",
  "Nathan",
  "Aaron",
  "Eli",
  "Hunter",
  "Connor",
  "Landon",
  "Adrian",
  "Asher",
  "Jonathan",
  "Caleb",
  "Jace",
  "Thomas",
  "Jeremiah",
  "Easton",
  "Hudson",
  "Robert",
  "Nolan",
  "Nicholas",
  "Ezra",
  "Colton",
  "Angel",
  "Brayden",
  "Jordan",
  "Dominic",
  "Austin",
  "Ian",
  "Adam",
  "Elias",
  "Jaxson",
  "Greyson",
  "Jose",
  "Ezekiel",
  "Carson",
  "Evan",
  "Maverick",
  "Bryson",
  "Jaxon",
  "Cooper",
  "Jason",
  "Parker",
  "Xavier",
  "Roman",
  "Kevin",
  "Bentley",
  "Tristan",
  "Damian",
  "Ashton",
  "Vincent",
  "Preston",
  "Kaleb",
  "Ryder",
];

const LAST_NAMES = [
  "Smith",
  "Johnson",
  "Williams",
  "Brown",
  "Jones",
  "Garcia",
  "Miller",
  "Davis",
  "Rodriguez",
  "Martinez",
  "Hernandez",
  "Lopez",
  "Wilson",
  "Anderson",
  "Thomas",
  "Taylor",
  "Moore",
  "Jackson",
  "Martin",
  "Lee",
  "Thompson",
  "White",
  "Harris",
  "Sanchez",
  "Clark",
  "Ramirez",
  "Lewis",
  "Robinson",
  "Walker",
  "Young",
  "Allen",
  "King",
  "Wright",
  "Scott",
  "Torres",
  "Nguyen",
  "Hill",
  "Flores",
  "Green",
  "Adams",
  "Nelson",
  "Baker",
  "Hall",
  "Rivera",
  "Campbell",
  "Mitchell",
  "Carter",
  "Roberts",
  "Gomez",
  "Phillips",
  "Evans",
  "Turner",
  "Diaz",
  "Parker",
  "Cruz",
  "Edwards",
  "Collins",
  "Reyes",
  "Stewart",
  "Morris",
  "Morales",
  "Murphy",
  "Cook",
  "Rogers",
  "Gutierrez",
  "Ortiz",
  "Morgan",
  "Cooper",
  "Peterson",
  "Bailey",
  "Reed",
  "Kelly",
  "Howard",
  "Ramos",
  "Kim",
  "Cox",
  "Ward",
  "Richardson",
  "Watson",
  "Brooks",
  "Chavez",
  "Wood",
  "James",
  "Bennett",
  "Gray",
  "Mendoza",
  "Ruiz",
  "Hughes",
  "Price",
  "Alvarez",
  "Castillo",
  "Sanders",
  "Patel",
  "Myers",
  "Long",
  "Ross",
  "Foster",
  "Jimenez",
  "Powell",
  "Jenkins",
  "Perry",
  "Russell",
  "Sullivan",
  "Bell",
  "Coleman",
  "Butler",
  "Henderson",
  "Barnes",
  "Gonzales",
  "Fisher",
  "Vasquez",
  "Simmons",
  "Romero",
  "Jordan",
  "Patterson",
  "Alexander",
  "Hamilton",
  "Graham",
  "Reynolds",
  "Griffin",
  "Wallace",
  "Moreno",
  "West",
  "Cole",
  "Hayes",
  "Bryant",
  "Herrera",
  "Gibson",
  "Ellis",
  "Tran",
  "Medina",
  "Aguilar",
  "Stevens",
  "Murray",
  "Ford",
  "Castro",
  "Marshall",
  "Owens",
  "Harrison",
  "Fernandez",
  "Mcdonald",
  "Woods",
  "Washington",
  "Kennedy",
  "Wells",
  "Vargas",
  "Henry",
  "Chen",
  "Freeman",
  "Webb",
  "Tucker",
  "Guzman",
  "Burns",
  "Crawford",
  "Olson",
  "Simpson",
  "Porter",
  "Hunter",
  "Gordon",
  "Mendez",
  "Silva",
  "Shaw",
  "Snyder",
  "Mason",
  "Dixon",
  "Munoz",
  "Hunt",
  "Hicks",
  "Holmes",
  "Palmer",
  "Wagner",
  "Black",
  "Robertson",
  "Boyd",
  "Rose",
  "Stone",
  "Salazar",
  "Fox",
  "Warren",
  "Mills",
  "Meyer",
  "Rice",
  "Schmidt",
  "Garza",
  "Daniels",
  "Ferguson",
  "Nichols",
  "Stephens",
  "Soto",
  "Weaver",
  "Ryan",
  "Gardner",
  "Payne",
  "Grant",
  "Dunn",
  "Kelley",
  "Spencer",
  "Hawkins",
  "Arnold",
  "Pierce",
  "Vazquez",
  "Hansen",
  "Peters",
  "Santos",
  "Hart",
  "Bradley",
  "Knight",
  "Elliott",
  "Cunningham",
  "Duncan",
  "Armstrong",
  "Hudson",
  "Carroll",
  "Lane",
  "Riley",
  "Andrews",
  "Alvarado",
  "Ray",
  "Delgado",
  "Berry",
  "Perkins",
  "Hoffman",
  "Johnston",
  "Matthews",
  "Pena",
  "Richards",
  "Contreras",
  "Willis",
  "Carpenter",
  "Lawrence",
  "Sandoval",
  "Guerrero",
  "George",
  "Chapman",
  "Rios",
  "Estrada",
  "Ortega",
  "Watkins",
  "Greene",
  "Nunez",
  "Wheeler",
  "Valdez",
  "Harper",
  "Lynch",
  "Barker",
  "Maldonado",
  "Zimmerman",
  "Paul",
  "Potter",
  "Obrien",
  "Casey",
  "Mccarthy",
  "Lucero",
  "Hodge",
  "Merritt",
  "Mata",
  "Strickland",
  "Anthony",
  "Cisneros",
  "Bond",
  "Kerr",
  "Duffy",
  "Valenzuela",
  "Ayala",
  "Valentine",
  "Mejia",
  "Gaines",
  "Horton",
  "Sheppard",
  "Berg",
  "Schroeder",
  "Fields",
  "Wiley",
  "Buck",
  "Glass",
  "Morton",
  "Singleton",
  "Briggs",
  "Parsons",
  "Mcintosh",
  "Dorsey",
  "Pineda",
  "Galloway",
  "Booth",
  "Kane",
  "Patton",
  "Lyons",
  "Cline",
  "Navarro",
  "Harrell",
  "Forbes",
  "Delacruz",
  "Colon",
  "Chandler",
  "Ingram",
  "Terry",
  "Hutchinson",
  "Brennan",
  "Cannon",
  "Cantrell",
  "Atkins",
  "Merritt",
  "Huffman",
  "Boyle",
  "Mayer",
  "Coffey",
  "Marsh",
  "Roach",
  "Joyce",
  "Vincent",
  "Frost",
  "Brady",
  "Andersen",
  "Workman",
  "Finley",
  "Mccall",
  "Gill",
  "Juarez",
  "Hoover",
  "Ware",
  "Brewer",
  "Barrera",
  "Orr",
  "Jacobson",
  "Gay",
  "Garner",
  "Acosta",
  "Franco",
  "Shields",
  "Rubio",
  "Wolf",
  "Chandler",
  "Daniel",
  "Norris",
  "Mccullough",
  "Holloway",
  "Floyd",
  "Hartman",
  "Brock",
  "Shaffer",
  "Doyle",
  "Sherman",
  "Saunders",
  "Wise",
  "Colon",
  "Gill",
  "Alvarado",
  "Greer",
  "Padilla",
  "Simon",
  "Waters",
  "Nunez",
  "Ballard",
  "Schwartz",
  "Mcbride",
  "Houston",
  "Christensen",
  "Klein",
  "Pratt",
  "Briggs",
  "Parsons",
  "Mclaughlin",
  "Zimmerman",
  "French",
  "Buchanan",
  "Moran",
  "Copeland",
  "Roy",
  "Pittman",
  "Brady",
  "Mccormick",
  "Holloway",
  "Brock",
  "Poole",
  "Frank",
  "Logan",
  "Owen",
  "Bass",
  "Marsh",
  "Drake",
  "Wong",
  "Jefferson",
  "Park",
  "Morton",
  "Abbott",
  "Sparks",
  "Patrick",
  "Norton",
  "Huff",
  "Clayton",
  "Massey",
  "Lloyd",
  "Figueroa",
  "Carson",
  "Bowers",
  "Roberson",
  "Barton",
  "Tran",
  "Lamb",
  "Harrington",
  "Casey",
  "Boone",
  "Cortez",
  "Clarke",
  "Mathis",
  "Singleton",
  "Wilkins",
  "Cain",
  "Bryan",
  "Underwood",
  "Hogan",
  "Mckenzie",
  "Collier",
  "Luna",
  "Phelps",
  "Mcguire",
  "Allison",
  "Bridges",
  "Wilkerson",
  "Nash",
  "Summers",
  "Atkins",
  "Wilcox",
  "Pitts",
  "Conley",
  "Marquez",
  "Burnett",
  "Richard",
  "Cochran",
  "Chase",
  "Davenport",
  "Hood",
  "Gates",
  "Clay",
  "Ayala",
  "Sawyer",
  "Roman",
  "Vazquez",
  "Dickerson",
  "Hodge",
  "Acosta",
  "Flynn",
  "Espinoza",
  "Nicholson",
  "Monroe",
  "Wolf",
  "Morrow",
  "Kirk",
  "Randall",
  "Anthony",
  "Whitaker",
  "Oconnor",
  "Skinner",
  "Ware",
  "Molina",
  "Kirby",
  "Huffman",
  "Fleming",
  "Hull",
  "Dickerson",
  "Curry",
  "Powers",
  "Schultz",
  "Walters",
  "Reid",
  "Willis",
  "Gilmore",
  "Benson",
  "Sharp",
  "Bowen",
  "Daniel",
  "Barber",
  "Cummings",
  "Hines",
  "Baldwin",
  "Griffith",
  "Valdez",
  "Hubbard",
  "Salinas",
  "Reeves",
  "Warner",
  "Stevenson",
  "Burgess",
  "Santos",
  "Tate",
  "Cross",
  "Garner",
  "Mann",
  "Mack",
  "Moss",
  "Thornton",
  "Dennis",
  "Mcgee",
  "Farmer",
  "Delgado",
  "Aguilar",
  "Vega",
  "Glover",
  "Manning",
  "Cohen",
  "Harmon",
  "Rodgers",
  "Robbins",
  "Newton",
  "Todd",
  "Blair",
  "Higgins",
  "Ingram",
  "Reese",
  "Cannon",
  "Strickland",
  "Townsend",
  "Potter",
  "Goodwin",
  "Walton",
  "Rowe",
  "Hampton",
  "Ortega",
  "Patton",
  "Swanson",
  "Joseph",
  "Francis",
  "Goodman",
  "Maldonado",
  "Yates",
  "Becker",
  "Erickson",
  "Hodges",
  "Rios",
  "Conner",
  "Adkins",
  "Webster",
  "Norman",
  "Horton",
  "Adkins",
  "Terry",
  "Conrad",
  "Gould",
  "Choi",
  "Moon",
  "Mccarty",
  "Pollard",
  "Melton",
  "Oconnell",
  "Lester",
  "Dillard",
  "Pollard",
  "Melton",
  "Oconnell",
  "Lester",
  "Dillard",
];

const seedSchema = z.object({
  userCount: z.number().int().min(1).max(50).default(5),
  resultsPerUser: z.number().int().min(1).max(20).default(3),
  subjects: z.string().min(1), // Comma-separated subjects
  scoreMin: z.number().int().min(0).max(100).default(60),
  scoreMax: z.number().int().min(0).max(100).default(100),
});

export interface SeedResult {
  success: boolean;
  usersCreated: number;
  resultsCreated: number;
  error?: string;
}

/**
 * Seed users and results for leaderboard testing
 * Only accessible to admins
 */
export async function seedUsersAndResults(
  input: z.infer<typeof seedSchema>
): Promise<SeedResult> {
  try {
    // Check admin role
    const session = await auth();
    if (!session?.user?.id || session.user.role !== "admin") {
      return {
        success: false,
        usersCreated: 0,
        resultsCreated: 0,
        error: "Unauthorized: Admin access required",
      };
    }

    // Validate input
    const validated = seedSchema.parse(input);

    // Parse subjects (comma-separated, trim whitespace)
    const subjectList = validated.subjects
      .split(",")
      .map((s) => s.trim())
      .filter((s) => s.length > 0 && s.length <= 64);

    if (subjectList.length === 0) {
      return {
        success: false,
        usersCreated: 0,
        resultsCreated: 0,
        error: "At least one valid subject is required",
      };
    }

    // Ensure scoreMin <= scoreMax
    const scoreMin = Math.min(validated.scoreMin, validated.scoreMax);
    const scoreMax = Math.max(validated.scoreMin, validated.scoreMax);

    const timestamp = Date.now();
    const usersToCreate = [];
    const profilesToCreate = [];
    const resultsToCreate = [];

    // Track used names to avoid duplicates
    const usedNames = new Set<string>();

    // Generate users with realistic names and varied result counts
    for (let i = 0; i < validated.userCount; i++) {
      const userId = randomUUID();

      // Generate unique realistic name
      let firstName: string;
      let lastName: string;
      let fullName: string;
      let attempts = 0;
      do {
        firstName = FIRST_NAMES[Math.floor(Math.random() * FIRST_NAMES.length)];
        lastName = LAST_NAMES[Math.floor(Math.random() * LAST_NAMES.length)];
        fullName = `${firstName} ${lastName}`;
        attempts++;
      } while (usedNames.has(fullName) && attempts < 100);
      usedNames.add(fullName);

      const email = `${firstName.toLowerCase()}.${lastName.toLowerCase()}.${timestamp}${i}@example.com`;

      usersToCreate.push({
        id: userId,
        name: fullName,
        email,
        createdAt: new Date(),
      });

      profilesToCreate.push({
        userId,
        persona: "student" as Persona,
        minor: false,
        guardianId: null,
        onboardingCompleted: true,
        createdAt: new Date(),
      });

      // Generate varied number of results per user for realistic leaderboard spread
      // Create a distribution: some users with many results (top performers),
      // some with average, some with fewer
      let resultCount: number;
      if (i < Math.floor(validated.userCount * 0.2)) {
        // Top 20%: high performers (2-3x average)
        resultCount = Math.floor(
          validated.resultsPerUser * (2 + Math.random())
        );
      } else if (i < Math.floor(validated.userCount * 0.5)) {
        // Next 30%: above average (1.5-2x average)
        resultCount = Math.floor(
          validated.resultsPerUser * (1.5 + Math.random() * 0.5)
        );
      } else if (i < Math.floor(validated.userCount * 0.8)) {
        // Next 30%: average (0.8-1.2x average)
        resultCount = Math.floor(
          validated.resultsPerUser * (0.8 + Math.random() * 0.4)
        );
      } else {
        // Bottom 20%: fewer results (0.5-0.8x average, minimum 1)
        resultCount = Math.max(
          1,
          Math.floor(validated.resultsPerUser * (0.5 + Math.random() * 0.3))
        );
      }

      // Generate results for this user
      // Distribute results across subjects with some users focusing on specific subjects
      for (let j = 0; j < resultCount; j++) {
        // Some users focus on one subject (70% chance), others spread across subjects
        const subject =
          j === 0 && Math.random() < 0.7
            ? subjectList[Math.floor(Math.random() * subjectList.length)]
            : subjectList[j % subjectList.length];

        const score = Math.floor(
          Math.random() * (scoreMax - scoreMin + 1) + scoreMin
        );

        resultsToCreate.push({
          id: randomUUID(),
          userId,
          subject,
          score,
          metadata: {
            seeded: true,
            seedTimestamp: timestamp,
          },
          createdAt: new Date(),
        });
      }
    }

    // Insert users
    if (usersToCreate.length > 0) {
      await db.insert(users).values(usersToCreate);
    }

    // Insert profiles
    if (profilesToCreate.length > 0) {
      await db.insert(usersProfiles).values(profilesToCreate);
    }

    // Insert results
    if (resultsToCreate.length > 0) {
      await db.insert(results).values(resultsToCreate);
    }

    return {
      success: true,
      usersCreated: usersToCreate.length,
      resultsCreated: resultsToCreate.length,
    };
  } catch (error) {
    console.error("[seed] Error seeding data:", error);
    return {
      success: false,
      usersCreated: 0,
      resultsCreated: 0,
      error:
        error instanceof Error
          ? error.message
          : "Failed to seed data. Check server logs.",
    };
  }
}

/**
 * Quick seed - creates 15 users with varied results for realistic demo leaderboard
 * Creates a good spread: top performers, average users, and beginners
 */
export async function quickSeed(): Promise<SeedResult> {
  return seedUsersAndResults({
    userCount: 15,
    resultsPerUser: 5, // Average - will be varied in the function
    subjects: "algebra,geometry,calculus,physics,chemistry",
    scoreMin: 60,
    scoreMax: 100,
  });
}
